.class public final LX/0S3b;
.super Ljava/lang/Object;
.source "SourceFile"

# interfaces
.implements LX/0oAW;


# instance fields
.field public final synthetic LIZ:Lcom/ss/android/ugc/aweme/shortvideo/ui/AutogeneratedCaptionLanguageSelectionFragment;


# direct methods
.method public constructor <init>(Lcom/ss/android/ugc/aweme/shortvideo/ui/AutogeneratedCaptionLanguageSelectionFragment;)V
    .locals 0

    iput-object p1, p0, LX/0S3b;->LIZ:Lcom/ss/android/ugc/aweme/shortvideo/ui/AutogeneratedCaptionLanguageSelectionFragment;

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


# virtual methods
.method public final LIZ()V
    .locals 2

    sget-object v0, Lcom/bytedance/tux/sheet/sheet/TuxSheet;->_pnsPageId:Ljava/lang/String;

    iget-object v1, p0, LX/0S3b;->LIZ:Lcom/ss/android/ugc/aweme/shortvideo/ui/AutogeneratedCaptionLanguageSelectionFragment;

    sget-object v0, LX/0o9r;->LIZ:LX/0o9r;

    invoke-static {v1, v0}, LX/0o9a;->LJFF(Landroidx/fragment/app/Fragment;LX/0o9n;)V

    return-void
.end method
