.class public final LX/0NN0;
.super Ljava/lang/Object;
.source "SourceFile"

# interfaces
.implements LX/0NNI;


# instance fields
.field public final LIZ:Ljava/lang/String;

.field public LIZIZ:Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;

.field public final LIZJ:Ljava/util/ArrayList;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/ArrayList<",
            "Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionDisplaySwitchRecord;",
            ">;"
        }
    .end annotation
.end field

.field public final LIZLLL:Ljava/util/ArrayList;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/ArrayList<",
            "Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionLangSwitchRecord;",
            ">;"
        }
    .end annotation
.end field

.field public final LJ:Ljava/util/LinkedHashMap;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/LinkedHashMap<",
            "Ljava/lang/String;",
            "Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionLoadInfo;",
            ">;"
        }
    .end annotation
.end field

.field public LJFF:Ljava/lang/String;

.field public LJI:Lcom/ss/android/ugc/aweme/feed/model/Aweme;


# direct methods
.method public static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method public constructor <init>(Ljava/lang/String;)V
    .locals 15

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    move-object/from16 v1, p1

    iput-object v1, p0, LX/0NN0;->LIZ:Ljava/lang/String;

    new-instance v0, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;

    const/4 v2, 0x0

    const/4 v4, 0x0

    const-wide/16 v11, 0x0

    const/16 v13, 0x7fe

    move-object v3, v2

    move v5, v4

    move v6, v4

    move-object v7, v2

    move-object v8, v2

    move-object v9, v2

    move-object v10, v2

    move-object v14, v2

    invoke-direct/range {v0 .. v14}, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/List;IIILjava/util/List;Ljava/util/List;Ljava/util/List;Ljava/lang/String;JILkotlin/jvm/internal/DefaultConstructorMarker;)V

    iput-object v0, p0, LX/0NN0;->LIZIZ:Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;

    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, LX/0NN0;->LIZJ:Ljava/util/ArrayList;

    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, LX/0NN0;->LIZLLL:Ljava/util/ArrayList;

    new-instance v0, Ljava/util/LinkedHashMap;

    invoke-direct {v0}, Ljava/util/LinkedHashMap;-><init>()V

    iput-object v0, p0, LX/0NN0;->LJ:Ljava/util/LinkedHashMap;

    const-string v0, ""

    iput-object v0, p0, LX/0NN0;->LJFF:Ljava/lang/String;

    return-void
.end method

.method public static LIZJ(Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;)Lcom/ss/android/ugc/aweme/service/perfetservice/OfflineCaptionInfo;
    .locals 6

    if-nez p0, :cond_0

    const/4 v0, 0x0

    return-object v0

    :cond_0
    invoke-static {}, LX/0gDn;->LJIIL()Z

    move-result v0

    const-string v3, ""

    if-eqz v0, :cond_2

    new-instance v1, Lcom/ss/android/ugc/aweme/service/perfetservice/OfflineCaptionInfo;

    invoke-virtual {p0}, Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;->getLanguageName()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {p0}, Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;->getSubId()I

    move-result v0

    invoke-static {v0}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    move-result-object v0

    if-eqz v0, :cond_1

    move-object v3, v0

    :cond_1
    sget-object v4, LX/0Pgk;->INSTANCE:LX/0Pgk;

    invoke-static {p0}, LX/0NNH;->LIZIZ(Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;)Z

    move-result v5

    invoke-virtual {p0}, Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;->isAutoGenerated()Z

    move-result p0

    invoke-direct/range {v1 .. v6}, Lcom/ss/android/ugc/aweme/service/perfetservice/OfflineCaptionInfo;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/List;ZZ)V

    return-object v1

    :cond_2
    new-instance v1, Lcom/ss/android/ugc/aweme/service/perfetservice/OfflineCaptionInfo;

    invoke-virtual {p0}, Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;->getLanguageName()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {p0}, Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;->getSubId()I

    move-result v0

    invoke-static {v0}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    move-result-object v0

    if-eqz v0, :cond_3

    move-object v3, v0

    :cond_3
    invoke-virtual {p0}, Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;->getUrl()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Ljava/util/Collections;->singletonList(Ljava/lang/Object;)Ljava/util/List;

    move-result-object v4

    invoke-static {p0}, LX/0NNH;->LIZIZ(Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;)Z

    move-result v5

    invoke-virtual {p0}, Lcom/ss/android/ugc/aweme/feed/model/CaptionItemModel;->isAutoGenerated()Z

    move-result p0

    invoke-direct/range {v1 .. v6}, Lcom/ss/android/ugc/aweme/service/perfetservice/OfflineCaptionInfo;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/List;ZZ)V

    return-object v1
.end method


# virtual methods
.method public final LIZ(Ljava/lang/String;LX/0NN5;LX/0NN6;)V
    .locals 30

    move-object/from16 v13, p0

    iget-object v0, v13, LX/0NN0;->LIZ:Ljava/lang/String;

    move-object/from16 v1, p1

    invoke-static {v0, v1}, Lkotlin/jvm/internal/Intrinsics;->LJFF(Ljava/lang/Object;Ljava/lang/Object;)Z

    move-result v0

    if-nez v0, :cond_0

    return-void

    :cond_0
    move-object/from16 v11, p2

    iget-object v1, v11, LX/0NN5;->LLILLL:Ljava/lang/String;

    sget-object v0, LX/0NME;->SWITCH_LANGUAGE:LX/0NME;

    invoke-virtual {v0}, LX/0NME;->getValue()Ljava/lang/String;

    move-result-object v0

    invoke-static {v1, v0}, Lkotlin/jvm/internal/Intrinsics;->LJFF(Ljava/lang/Object;Ljava/lang/Object;)Z

    move-result v16

    if-eqz v16, :cond_1

    iget-object v1, v13, LX/0NN0;->LJ:Ljava/util/LinkedHashMap;

    iget-object v0, v11, LX/0NN5;->LLILL:Ljava/lang/String;

    invoke-virtual {v1, v0}, Ljava/util/HashMap;->containsKey(Ljava/lang/Object;)Z

    move-result v0

    if-eqz v0, :cond_1

    return-void

    :cond_1
    invoke-static {}, Ljava/lang/System;->currentTimeMillis()J

    move-result-wide v0

    iget-object v2, v13, LX/0NN0;->LIZLLL:Ljava/util/ArrayList;

    invoke-virtual {v2}, Ljava/util/ArrayList;->isEmpty()Z

    move-result v2

    move-object/from16 v12, p3

    if-eqz v2, :cond_2

    iget-object v14, v13, LX/0NN0;->LIZIZ:Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;

    iget-object v2, v12, LX/0NN6;->LLILZLL:Ljava/lang/Integer;

    if-eqz v2, :cond_4

    invoke-virtual {v2}, Ljava/lang/Integer;->intValue()I

    move-result v22

    :goto_0
    iget v2, v11, LX/0NN5;->LLILZ:I

    move/from16 v17, v2

    iget-object v15, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->awemeId:Ljava/lang/String;

    iget-object v10, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->originalLangName:Ljava/lang/String;

    iget-object v9, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->offlineCaptionsInfo:Ljava/util/List;

    iget v8, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->realtimeCaptionCount:I

    iget-object v7, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->captionLoadRecords:Ljava/util/List;

    iget-object v6, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->captionDisplaySwitchRecords:Ljava/util/List;

    iget-object v5, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->captionLangSwitchRecords:Ljava/util/List;

    iget-object v4, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->extraErrorInfo:Ljava/lang/String;

    iget-wide v2, v14, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->firstFrameRenderedTimestamp:J

    move-wide/from16 v28, v2

    move/from16 v23, v8

    move-object/from16 v24, v7

    move-object/from16 v25, v6

    move-object/from16 v26, v5

    move-object/from16 v27, v4

    move-object/from16 v20, v9

    move/from16 v21, v17

    move-object/from16 v18, v15

    move-object/from16 v19, v10

    move-object/from16 v17, v14

    invoke-virtual/range {v17 .. v29}, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;->copy(Ljava/lang/String;Ljava/lang/String;Ljava/util/List;IIILjava/util/List;Ljava/util/List;Ljava/util/List;Ljava/lang/String;J)Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;

    move-result-object v2

    iput-object v2, v13, LX/0NN0;->LIZIZ:Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionBehaviorInfo;

    iget-object v5, v13, LX/0NN0;->LIZLLL:Ljava/util/ArrayList;

    new-instance v4, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionLangSwitchRecord;

    iget-object v3, v11, LX/0NN5;->LLILL:Ljava/lang/String;

    iget-object v2, v11, LX/0NN5;->LL:Ljava/lang/String;

    invoke-direct {v4, v0, v1, v3, v2}, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionLangSwitchRecord;-><init>(JLjava/lang/String;Ljava/lang/String;)V

    invoke-virtual {v5, v4}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    iget-object v2, v11, LX/0NN5;->LLILL:Ljava/lang/String;

    iput-object v2, v13, LX/0NN0;->LJFF:Ljava/lang/String;

    :cond_2
    iget-object v3, v11, LX/0NN5;->LLILLJJLI:Ljava/lang/String;

    sget-object v2, LX/0N0X;->REALTIME:LX/0N0X;

    invoke-virtual {v2}, LX/0N0X;->getValue()Ljava/lang/String;

    move-result-object v2

    invoke-static {v3, v2}, Lkotlin/jvm/internal/Intrinsics;->LJFF(Ljava/lang/Object;Ljava/lang/Object;)Z

    move-result v2

    iget-object v14, v11, LX/0NN5;->LL:Ljava/lang/String;

    iget-object v6, v11, LX/0NN5;->LLILIL:Ljava/lang/String;

    iget-object v4, v13, LX/0NN0;->LJI:Lcom/ss/android/ugc/aweme/feed/model/Aweme;

    if-eqz v2, :cond_3

    if-eqz v16, :cond_3

    if-eqz v4, :cond_3

    sget-object v3, LX/0Mzj;->LIZ:LX/0N3B;

    iget-object v2, v11, LX/0NN5;->LLILL:Ljava/lang/String;

    invoke-virtual {v3, v4, v2}, LX/0N3B;->LJJJJI(Lcom/ss/android/ugc/aweme/feed/model/Aweme;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v14

    move-object v6, v14

    :cond_3
    sget-object v2, LX/0NN9;->Companion:LX/0NNK;

    iget v7, v12, LX/0NN6;->LL:I

    invoke-virtual {v2}, Ljava/lang/Object;->getClass()Ljava/lang/Class;

    invoke-static {}, LX/0NN9;->values()[LX/0NN9;

    move-result-object v5

    array-length v4, v5

    const/4 v3, 0x0

    :goto_1
    const/4 v8, 0x0

    if-ge v3, v4, :cond_5

    aget-object v10, v5, v3

    invoke-virtual {v10}, LX/0NN9;->getValue()I

    move-result v2

    if-eq v2, v7, :cond_6

    add-int/lit8 v3, v3, 0x1

    goto :goto_1

    :cond_4
    const/16 v22, 0x0

    goto/16 :goto_0

    :cond_5
    move-object v10, v8

    :cond_6
    iget-object v7, v13, LX/0NN0;->LJ:Ljava/util/LinkedHashMap;

    iget-object v5, v11, LX/0NN5;->LLILL:Ljava/lang/String;

    iget-object v4, v11, LX/0NN5;->LLILLJJLI:Ljava/lang/String;

    invoke-static {}, LX/0Y9f;->LIZ()Ljava/lang/StringBuilder;

    move-result-object v3

    if-eqz v10, :cond_8

    invoke-virtual {v10}, LX/0NN9;->getValue()I

    move-result v2

    invoke-static {v2}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v2

    :goto_2
    invoke-virtual {v3, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string v9, ": "

    invoke-virtual {v3, v9}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    if-eqz v10, :cond_7

    invoke-virtual {v10}, LX/0NN9;->getDescription()Ljava/lang/String;

    move-result-object v8

    :cond_7
    invoke-virtual {v3, v8}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-static {v3}, LX/0Y9f;->LIZIZ(Ljava/lang/StringBuilder;)Ljava/lang/String;

    move-result-object v16

    iget v3, v12, LX/0NN6;->LLILIL:I

    invoke-static {}, LX/0Y9f;->LIZ()Ljava/lang/StringBuilder;

    move-result-object v8

    iget-object v2, v12, LX/0NN6;->LLILLIZIL:Ljava/lang/Integer;

    invoke-virtual {v8, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v8, v9}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    iget-object v2, v12, LX/0NN6;->LLILZIL:Ljava/lang/String;

    invoke-virtual {v8, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-static {v8}, LX/0Y9f;->LIZIZ(Ljava/lang/StringBuilder;)Ljava/lang/String;

    move-result-object v18

    iget-object v13, v11, LX/0NN5;->LLILL:Ljava/lang/String;

    new-instance v12, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionLoadInfo;

    const/16 v20, -0x1

    move-wide/from16 v21, v0

    move-object/from16 v19, v4

    move/from16 v17, v3

    move-object v15, v6

    invoke-direct/range {v12 .. v22}, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionLoadInfo;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;IJ)V

    invoke-virtual {v7, v5, v12}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    return-void

    :cond_8
    move-object v2, v8

    goto :goto_2
.end method

.method public final LIZIZ(Ljava/lang/String;LX/0NN5;I)V
    .locals 12

    iget-object v0, p0, LX/0NN0;->LIZ:Ljava/lang/String;

    invoke-static {v0, p1}, Lkotlin/jvm/internal/Intrinsics;->LJFF(Ljava/lang/Object;Ljava/lang/Object;)Z

    move-result v0

    if-nez v0, :cond_0

    return-void

    :cond_0
    iget-object v0, p0, LX/0NN0;->LJ:Ljava/util/LinkedHashMap;

    invoke-virtual {v0}, Ljava/util/HashMap;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_1

    iget-object v1, p0, LX/0NN0;->LJ:Ljava/util/LinkedHashMap;

    iget-object v0, p2, LX/0NN5;->LLILL:Ljava/lang/String;

    invoke-virtual {v1, v0}, Ljava/util/LinkedHashMap;->get(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0

    if-nez v0, :cond_2

    :cond_1
    const-string v8, "receive first caption but no receive load end?"

    new-instance v1, LX/0NN6;

    sget-object v0, LX/0NN9;->SUCCESS:LX/0NN9;

    invoke-virtual {v0}, LX/0NN9;->getValue()I

    move-result v2

    const/4 v3, 0x0

    const/4 v0, -0x1

    invoke-static {v0}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v4

    invoke-static {v0}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v5

    invoke-static {v0}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v6

    invoke-static {v0}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v7

    const/4 v9, 0x0

    const v11, 0xff04

    move-object v10, v9

    invoke-direct/range {v1 .. v11}, LX/0NN6;-><init>(IILjava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/String;I)V

    invoke-virtual {p0, p1, p2, v1}, LX/0NN0;->LIZ(Ljava/lang/String;LX/0NN5;LX/0NN6;)V

    :cond_2
    iget-object v1, p0, LX/0NN0;->LJ:Ljava/util/LinkedHashMap;

    iget-object v0, p2, LX/0NN5;->LLILL:Ljava/lang/String;

    invoke-virtual {v1, v0}, Ljava/util/LinkedHashMap;->get(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionLoadInfo;

    if-eqz v0, :cond_3

    invoke-virtual {v0, p3}, Lcom/ss/android/ugc/aweme/service/perfetservice/CaptionLoadInfo;->setFirstCaptionLoadToDisplayTime(I)V

    :cond_3
    return-void
.end method
