.class public final Lcom/ss/android/ugc/aweme/shortvideo/ui/AutogeneratedCaptionLanguageSelectionViewModel;
.super Landroidx/lifecycle/ViewModel;
.source "SourceFile"


# instance fields
.field public final LL:Landroidx/lifecycle/MutableLiveData;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Landroidx/lifecycle/MutableLiveData<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field

.field public final LLILIL:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "LX/0S3Z;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>()V
    .locals 7

    invoke-direct {p0}, Landroidx/lifecycle/ViewModel;-><init>()V

    new-instance v0, Landroidx/lifecycle/MutableLiveData;

    invoke-direct {v0}, Landroidx/lifecycle/MutableLiveData;-><init>()V

    iput-object v0, p0, Lcom/ss/android/ugc/aweme/shortvideo/ui/AutogeneratedCaptionLanguageSelectionViewModel;->LL:Landroidx/lifecycle/MutableLiveData;

    invoke-static {}, LX/0Ae1;->LIZ()[Lcom/ss/android/ugc/aweme/shortvideo/experiment/AutogeneratedCaptionLanguageSelection;

    move-result-object v6

    new-instance v5, Ljava/util/ArrayList;

    array-length v0, v6

    invoke-direct {v5, v0}, Ljava/util/ArrayList;-><init>(I)V

    array-length v4, v6

    const/4 v3, 0x0

    :goto_0
    if-ge v3, v4, :cond_0

    aget-object v0, v6, v3

    new-instance v2, LX/0S3Z;

    invoke-virtual {v0}, Lcom/ss/android/ugc/aweme/shortvideo/experiment/AutogeneratedCaptionLanguageSelection;->getCode()Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0}, Lcom/ss/android/ugc/aweme/shortvideo/experiment/AutogeneratedCaptionLanguageSelection;->getLocalName()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v2, v1, v0}, LX/0S3Z;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    invoke-virtual {v5, v2}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    add-int/lit8 v3, v3, 0x1

    goto :goto_0

    :cond_0
    iput-object v5, p0, Lcom/ss/android/ugc/aweme/shortvideo/ui/AutogeneratedCaptionLanguageSelectionViewModel;->LLILIL:Ljava/util/List;

    return-void
.end method
